### PR TITLE
reframe "Autistic Spectrum Disorder"

### PR DESCRIPTION
**Pull request by niccokunzmann**
I rephrased this because disorder is judgemental in my eyes and Autism can be not just a disorder but also a strength. But there might be a good source for naming it a disorder - e.g. a link to a study and therefore this might be a valid name.

Is there a source or is it ok to merge?

### CODE REVIEW

**Comment by jazmichaelking** [comment]
I've reached out to Autism Wales to get input on appropriate terminology.

**Comment by niccokunzmann** [comment]
I also talked to my partner and she said that Autism Spectrum Disorder means that it acctually impacts your life to a certain level. 
So what I think now, while it might be correctly applied, it could be hard to understand that not everyone on the autistic spectrum would classify under disorder. Also, I do notice how I appreciate the Content Wall to hide intense content, I do not think I am classified in any way nor would I be within disorder - maybe.

In that sense it is a sign of consideration to use the content wall so people have more choice when reading and that might be crucial in some cases.
For me, it took me 15 minutes to digest a conversation and formulate a connecting reply.

So, I think, instead of saying this is statistics and here is a term, it can add more understanding when there is a short story about why people actually value the content wall and how it enables them to use the platform. That might be more connecting than numbers. Numbers don't provide a feel for me anyway. 

Maybe, in the answer that you will get, there is something like that. While the facts might be correct - it is how we use them that matters most.

Thanks for answering - it helped me clarify my reasoning.

**Comment by jazmichaelking** [comment]
CWs are sometimes for the reader, sometimes for the writer, this is a good rundown of the general approach: https://wirebird.com/artidocs/content-warnings

**Comment by TCMuffin** [comment]
This guide to using CWs is an incredibly useful resource for a newbie mastodon user feeling her way through the customs of this amazing space.

Perhaps a link to it could be added to @jazmichaelking's "Getting Started" blog?

**Comment by jazmichaelking** [comment]
Updated to Autism Spectrum condition

**Pull request closed without merging**
